package bancard

// Transaction response codes returned in the response_code field of
// confirmations, as documented in the VPOS specification. Descriptions
// are the official ones (in Spanish).

// responseCodeDescriptions maps the transaction response code to its
// official description. Codes not present in the map are unknown to this
// client version; ResponseCodeDescription returns "" for them.
var responseCodeDescriptions = map[string]string{
	"00": "TRANSACCIÓN APROBADA",
	"01": "LLAMAR AL BANCO EMISOR",
	"02": "LLAMAR AL BANCO EMISOR",
	"03": "COMERCIO INVÁLIDO",
	"04": "RETENER TARJETA",
	"05": "NO APROBADA",
	"07": "RETENER TARJETA - CONDICION ESPECIAL",
	"08": "APROBAR - IDENTIFICACION",
	"12": "TRANSACCIÓN INVÁLIDA",
	"13": "MONTO INVÁLIDO",
	"14": "NÚMERO DE TARJETA INVÁLIDO",
	"15": "EMISOR INVÁLIDO",
	"19": "REINGRESE TRANSACCIÓN",
	"20": "RESPUESTA INVALIDA",
	"28": "NRO.TARJETA NO ENCONTRADO",
	"30": "ERROR EN FORMATO DE MENSAJE",
	"31": "BANCO EMISOR DESCONOCIDO",
	"33": "FECHA DE VENCIMIENTO ERRONEA",
	"34": "POSIBLE FRAUDE",
	"35": "RETENER TARJETA - PEDIDO DEL BCO. EMISOR",
	"36": "BANCO EMISOR INACTIVO",
	"38": "LIMITE DE INTENTOS DE CLAVE EXCEDIDO",
	"39": "NO CUENTA CON ESA TARJETA",
	"41": "PERDIDA DE TARJETA - RETENER",
	"43": "TARJETA ROBADA - RETENGA TARJETA",
	"45": "NO EXISTE LA CUENTA",
	"46": "EMISOR/BANCO NO RESPONDIO EN 49 SEGUNDOS",
	"47": "BCO.NEGOCIO O ATM NO RESPONDIO EN 49 SEG",
	"49": "OPERACION NO ACEPTADA EN CUOTAS",
	"5C": "TRN NO SOPORTADA-BLOQUEADA POR EL EMISOR",
	"51": "NO APROBADA-INSUF.DE FONDOS",
	"52": "NO APROBADA - NO EXISTE CUENTA CORRIENTE",
	"53": "NO APROBADA - NO EXISTE CUENTA AHORRO",
	"54": "TARJETA VENCIDA",
	"55": "CLAVE INVALIDA",
	"57": "TRANSACCION NO PERMITIDA",
	"58": "NO HABILITADA PARA ESTA TERMINAL",
	"59": "NO APROBADO - POSIBLE FRAUDE",
	"60": "NO APROBADO - CONSULTE PROCESADOR ADQUIR",
	"61": "EXCEDE MONTO LIMITE",
	"62": "NO APROBADA - TARJETA RESTRINGIDA",
	"63": "VIOLACION DE SEGURIDAD",
	"65": "EXCEDE CANTIDAD DE OPERACIONES",
	"66": "LLAMAR SEGURIDAD DEL PROCESADOR ADQUIR.",
	"70": "NEGOCIO EN MORA/FACTURA PENDIENTE",
	"71": "OPERACIÓN YA EXTORNADA",
	"72": "FECHA INVALIDA",
	"73": "CODIGO DE SEGURIDAD INVALIDO",
	"75": "EXCEDE LIMITE DE INTENTOS DE PIN - NO AP",
	"77": "EL CLIENTE NO TIENE CLAVE TODAVIA",
	"78": "CUENTA INACTIVA - PRIMER USO",
	"79": "CLAVE CAMBIADA",
	"80": "CLAVE ACTIVADA O CAMBIADA",
	"81": "ERROR CRIPTOGRAFICO EN EL PIN",
	"82": "ERROR DE AUTENTICACION",
	"83": "FRAUD/SECURITY - RESPUESTA DE LA MARCA",
	"85": "APROBADO - SIN IMPACTO FINANCIERO",
	"86": "IMPOSIBLE VERIFICAR PIN",
	"87": "TERMINADA LA RECONCILIACION DEL DIA",
	"88": "ERROR CRIPTOGRAFICO",
	"89": "POSICION FINANCIERA NO VERIFICABLE",
	"9G": "TARJETA BLOQUEADA-CONTACTE AL EMISOR",
	"90": "SWITCHER EN CIERRE - INTENTE EN 5 MINS.",
	"91": "EMISOR EN CIERRE - INTENTE OTRA VEZ",
	"92": "EMISOR DESCONECTADO - PROBLEMAS EN LINEA",
	"93": "NO APROBADO - VIOLACION DE LEY",
	"94": "TRANSACCION DUPLICADA - NO APROBADO",
	"96": "EMISOR DE LA TARJETA FUERA DE SERVICIO",
	"98": "BANCO DEL NEGOCIO/ATM FUERA DE SERVICIO",
	"99": "TRANSACCION EXTORNADA",
}

// ResponseCodeDescription returns the official description for a
// transaction response code (e.g. ResponseCodeDescription("51")), or an
// empty string for unknown codes. The description is in Spanish, as
// published by Bancard.
func ResponseCodeDescription(code string) string {
	return responseCodeDescriptions[code]
}
